{0x00, "No debugging"},
{0x01, "Verbose error reporting"},
{0x02, "Debug initialization"},
{0x04, "Debug socket operations"},
{0x08, "Debug client input"},
{0x10, "Debug client arrival/depart"},
{0x20, "Debug client commands"},
{0x40, "Debug channel operations"},