{ DEBUG_NONE, "No debugging"},
{ DEBUG_ERRS, "Verbose error reporting"},
{ DEBUG_INIT, "Debug initialization"},
{ DEBUG_SOCKETS, "Debug socket operations"},
{ DEBUG_SPLIT, "Debug message splitting"},
{ DEBUG_INPUT, "Debug client input"},
{ DEBUG_CLIENTS, "Debug client arrival/depart"},
{ DEBUG_CHANNELS, "Debug channel operations"},
{ DEBUG_REPLIES, "Debug server replies"},
